export const resList=[{
    data: {
      id: "557923",
      name: "Ganesham Fast Food",
      cloudinaryImageId: "ybbwkjnc5kdc2kihwsxo",
      locality: "New Market",
      areaName: "City Center",
      costForTwo: "₹300 for two",
      cuisines: ["Bakery", "Fast Food", "Desserts"],
      avgRating: 4.3,
      parentId: "7054",
      avgRatingString: "4.3",
    },
  },
  {
    data: {
      id: "557924",
      name: "New Inn Restaurant",
      cloudinaryImageId: "zcbeksptp9imnvvygmrn",
      locality: "MP Nagar",
      areaName: "Commercial Complex",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Fast Food"],
      avgRating: 4.2,
      parentId: "7055",
      avgRatingString: "4.2",
    },
  },
  {
    data: {
      id: "557925",
      name: "Sharma Bhojnalaya - Bus Stand Jawahar Chowk",
      cloudinaryImageId: "1641ddd08c8c4a31e86522328f5f8465",
      locality: "Arera Colony",
      areaName: "Residential Area",
      costForTwo: "₹250 for two",
      cuisines: ["Bakery", "Desserts"],
      avgRating: 4.6,
      parentId: "7056",
      avgRatingString: "4.6",
    },
  },
  {
    data: {
      id: "557926",
      name: "Zam Zam Fast Food",
      cloudinaryImageId: "7e3dcd737f0251895d6b50e5a17fca33",
      locality: "Bhopal Junction",
      areaName: "Railway Station",
      costForTwo: "₹450 for two",
      cuisines: ["Pizzas", "Pastas"],
      avgRating: 4.4,
      parentId: "7057",
      avgRatingString: "4.4",
    },
  },
  {
    data: {
      id: "557927",
      name: "Sagar Gaire",
      cloudinaryImageId: "eanb1laoe96xa3xr4nuq",
      locality: "Habibganj",
      areaName: "Commercial Area",
      costForTwo: "₹380 for two",
      cuisines: ["Chinese", "Continental"],
      avgRating: 4.1,
      parentId: "7058",
      avgRatingString: "4.1",
    },
  },
  {
    data: {
      id: "557928",
      name: "Sharma & Vishnu Fast Food",
      cloudinaryImageId: "xtjilr4hbushoxflffjm",
      locality: "Maharana Pratap Nagar",
      areaName: "Shopping Complex",
      costForTwo: "₹320 for two",
      cuisines: ["Snacks", "Fast Food"],
      avgRating: 4.3,
      parentId: "7059",
      avgRatingString: "4.3",
    },
  },
  {
    data: {
      id: "557929",
      name: "Bapu Ki Kutia",
      cloudinaryImageId: "rumvx9pfc56tbez1wovn",
      locality: "TT Nagar",
      areaName: "Market Area",
      costForTwo: "₹280 for two",
      cuisines: ["Bakery", "Desserts"],
      avgRating: 4.7,
      parentId: "7060",
      avgRatingString: "4.7",
    },
  },
  {
    data: {
      id: "557930",
      name: "Sharma Bhojnalaya Jawahar chowk",
      cloudinaryImageId: "2bac7a35febc2ae024028977b0e0ea82",
      locality: "Shahpura",
      areaName: "Residential Zone",
      costForTwo: "₹380 for two",
      cuisines: ["Chinese", "Fast Food"],
      avgRating: 4.2,
      parentId: "7061",
      avgRatingString: "4.2",
    },
  },
  {
    data: {
      id: "557931",
      name: "Food Nation",
      cloudinaryImageId: "hhkyjeydzhrvtnbmpclu",
      locality: "10 Number Market",
      areaName: "Local Market",
      costForTwo: "₹420 for two",
      cuisines: ["Pizzas", "Pastas"],
      avgRating: 4.5,
      parentId: "7062",
      avgRatingString: "4.5",
    },
  },
  {
    data: {
      id: "557932",
      name: "Bake N Shake",
      cloudinaryImageId: "ogej1e2xxku5bhfafdcw",
      locality: "Habibganj",
      areaName: "Commercial Zone",
      costForTwo: "₹350 for two",
      cuisines: ["Continental", "Bakery"],
      avgRating: 4.4,
      parentId: "7063",
      avgRatingString: "4.4",
    },
  }
   ]
